version: "3.7"

services:
  mysql-db:
    image: bcemsume/bisu-mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 1Q2w3e4r
      MYSQL_PASSWORD: 1Q2w3e4r
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - bisu-network
  node-app:
    image: bcemsume/bisu-api
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "4000:3000"
    expose:
      - "4000"
    networks:
      - bisu-network
  web-client:
    image: bcemsume/bisu-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3333:5000"
    expose:
      - "3333"
    networks:
      - bisu-network
networks:
  bisu-network:
    driver: bridge
